PROJECT = app
OPT = -Os
CFILES += main.c md5.c
LIB_DIR=../../lib/
USE_LIB=0
CFLAGS+=-Wno-strict-prototypes -Wno-missing-prototypes -Wno-unused-parameter -ffixed-r9 -ffixed-r10 -ffixed-r11 -ffixed-r12

include $(LIB_DIR)/rules.mk
