[fullflashes]
# siemens-cx75 = "~/Documents/Siemens/backup/emu/CX75.bin"
# siemens-el71 = "~/Documents/Siemens/backup/emu/EL71.bin"
# siemens-e71 = "~/Documents/Siemens/backup/emu/E71.bin"
# siemens-c81 = "~/Documents/Siemens/backup/emu/C81.bin"
# siemens-sl75 = "~/Documents/Siemens/backup/emu/SL75.bin"
# lg-ke970 = "~/Documents/LG/ke970_v10d.bin"
