#!/usr/bin/env perl
use strict;
use warnings;

use File::Spec;
use FindBin qw($RealBin);
use lib $RealBin;
use DspLzss qw(compress_blocks decompress_blocks);

sub read_file {
	my ($path) = @_;
	open my $file, '<:raw', $path or die "Cannot read $path: $!\n";
	local $/;
	return <$file>;
}

sub write_byte_array {
	my ($file, $name, $data) = @_;
	print {$file} "static const uint8_t $name\[\] = {\n";
	for (my $offset = 0; $offset < length($data); $offset += 16) {
		my @bytes = unpack 'C*', substr($data, $offset, 16);
		print {$file} "\t", join(', ', map { sprintf '0x%02x', $_ } @bytes), ",\n";
	}
	print {$file} "};\n";
}

sub write_integer_array {
	my ($file, $type, $name, $values) = @_;
	print {$file} "static const $type $name\[\] = {\n";
	my @remaining = @$values;
	while (@remaining) {
		my @line = splice @remaining, 0, 12;
		print {$file} "\t", join(', ', @line), ",\n";
	}
	print {$file} "};\n";
}

sub write_packed_file {
	my ($path, $prefix, $blocks, $preamble) = @_;
	my ($packed, $offsets, $sizes, $maximum_size) = compress_blocks(@$blocks);
	my @unpacked = decompress_blocks($packed, $offsets, $sizes);
	for my $block (0 .. $#$blocks) {
		die "$path: compressed block $block does not round-trip\n" if $unpacked[$block] ne $blocks->[$block];
	}
	my $temporary_path = "$path.$$";
	open my $output, '>', $temporary_path or die "Cannot write $temporary_path: $!\n";
	print {$output} "$preamble\n";
	print {$output} "#define ${prefix}_PACKED 1\n";
	print {$output} "#define ${prefix}_MAX_SIZE $maximum_size\n";
	write_byte_array($output, "${prefix}_DATA", $packed);
	write_integer_array($output, 'uint32_t', "${prefix}_OFFSETS", $offsets);
	write_integer_array($output, 'uint16_t', "${prefix}_SIZES", $sizes);
	close $output or die "Cannot close $temporary_path: $!\n";
	rename $temporary_path, $path or die "Cannot replace $path: $!\n";
	chmod 0644, $path or die "Cannot chmod $path: $!\n";
	return length($packed);
}

sub read_cases {
	my ($directory) = @_;
	my $path = File::Spec->catfile($directory, 'instructions-cases.inc');
	my $cases = read_file($path);
	my ($shard_count) = $cases =~ /^#define DSP_INSTRUCTION_SHARD_COUNT (\d+)$/m;
	my ($record_words) = $cases =~ /^#define DSP_INSTRUCTION_RECORD_WORDS (\d+)$/m;
	my ($shard_cases_text) = $cases =~ /static const uint16_t DSP_INSTRUCTION_SHARD_CASES\[\] = \{(.*?)\};/s;
	die "Cannot read shard metadata from $path\n"
		unless defined $shard_count && defined $record_words && defined $shard_cases_text;
	my @shard_cases = $shard_cases_text =~ /(\d+)/g;
	die "$path: expected $shard_count shard sizes, found " . scalar(@shard_cases) . "\n"
		if @shard_cases != $shard_count;
	return ($shard_count, $record_words, \@shard_cases);
}

sub pack_images {
	my ($directory, $shard_count) = @_;
	my $generated_directory = File::Spec->catdir($directory, 'generated');
	my @images;
	for my $shard (0 .. $shard_count - 1) {
		my $path = File::Spec->catfile($generated_directory, "instructions-image-$shard.inc");
		my $source = read_file($path);
		my @bytes = map { hex } $source =~ /0x([0-9a-fA-F]{2})/g;
		die "$path: image is empty\n" unless @bytes;
		push @images, pack('C*', @bytes);
	}
	my $path = File::Spec->catfile($directory, 'instructions-images-packed.inc');
	my $packed_size = write_packed_file($path, 'DSP_INSTRUCTION_IMAGES', \@images,
		'// Generated by pack_instructions.pl.');
	printf "Packed DSP1 images: %u -> %u bytes\n", length(join('', @images)), $packed_size;
}

sub pack_golden {
	my ($directory, $record_words, $shard_cases) = @_;
	my $source_path = File::Spec->catfile($directory, 'instructions-golden.inc');
	my $source = read_file($source_path);
	my ($count) = $source =~ /^#define DSP_INSTRUCTION_GOLDEN_COUNT (\d+)$/m;
	die "Cannot read golden count from $source_path\n" unless defined $count;
	my $path = File::Spec->catfile($directory, 'instructions-golden-packed.inc');
	if ($count == 0) {
		my $temporary_path = "$path.$$";
		open my $output, '>', $temporary_path or die "Cannot write $temporary_path: $!\n";
		print {$output} "// Generated by pack_instructions.pl.\n";
		print {$output} "#define DSP_INSTRUCTION_GOLDEN_COUNT 0\n";
		print {$output} "static const uint16_t DSP_INSTRUCTION_GOLDEN[1][DSP_INSTRUCTION_RECORD_WORDS];\n";
		close $output or die "Cannot close $temporary_path: $!\n";
		rename $temporary_path, $path or die "Cannot replace $path: $!\n";
		chmod 0644, $path or die "Cannot chmod $path: $!\n";
		return;
	}
	my @words = map { hex } $source =~ /0x([0-9a-fA-F]{4})/g;
	die "$source_path: expected " . ($count * $record_words) . ' words, found ' . scalar(@words) . "\n"
		if @words != $count * $record_words;
	my $data = pack('v*', @words);
	my @blocks;
	my $offset = 0;
	for my $cases (@$shard_cases) {
		my $size = $cases * $record_words * 2;
		push @blocks, substr($data, $offset, $size);
		$offset += $size;
	}
	die "$source_path: shard sizes cover $offset bytes, expected " . length($data) . "\n"
		if $offset != length($data);
	my $packed_size = write_packed_file($path, 'DSP_INSTRUCTION_GOLDEN', \@blocks,
		"// Generated by pack_instructions.pl.\n#define DSP_INSTRUCTION_GOLDEN_COUNT $count");
	printf "Packed DSP golden: %u -> %u bytes\n", length($data), $packed_size;
}

my $golden_only = @ARGV && $ARGV[0] eq '--golden';
shift @ARGV if $golden_only;
die "usage: $0 [--golden] [DIRECTORY]\n" if @ARGV > 1;
my $directory = @ARGV ? $ARGV[0] : $RealBin;
my ($shard_count, $record_words, $shard_cases) = read_cases($directory);
pack_images($directory, $shard_count) unless $golden_only;
pack_golden($directory, $record_words, $shard_cases);
