#!/usr/bin/env perl
use warnings;
use strict;
use File::Basename;
use File::Path qw(make_path);

sub readFile {
	my ($path) = @_;
	open my $fp, '<:raw', $path or die "open($path): $!";
	local $/;
	my $data = <$fp>;
	close $fp;
	return $data;
}

sub dumpHex {
	my ($data) = @_;
	my @lines;
	my @line;
	for (my $i = 0; $i < length($data); $i++) {
		push @line, sprintf("0x%02X", ord(substr($data, $i, 1)));
		if (@line >= 16) {
			push @lines, [@line];
			@line = ();
		}
	}
	push @lines, [@line] if @line;
	return "\t".join("\n\t", map { join(", ", @$_)."," } @lines)."\n";
}

die "Usage: $0 QEMU_GEN_DIR\n" if @ARGV != 1;
my $output_dir = $ARGV[0];
my $rom_dir = dirname(__FILE__).'/../rom/dsp';
my $generator = 'tools/'.basename($0);
my @images;
for my $program_path (sort glob "$rom_dir/*-program-rom.bin") {
	my ($rom_version) = $program_path =~ m{/([0-9a-fA-F]{4})-program-rom\.bin$};
	next if !defined $rom_version;
	$rom_version = lc($rom_version);
	my $data_path = "$rom_dir/$rom_version-data-rom.bin";
	my $program = readFile($program_path);
	my $data = readFile($data_path);
	push @images, {
		rom_version	=> $rom_version,
		program		=> $program,
		data		=> $data,
	};
}
die "No MASK ROM images found in $rom_dir" if !@images;

make_path($output_dir);
open my $header, '>', "$output_dir/dsp_rom.h" or die "open($output_dir/dsp_rom.h): $!";
print $header qq|/* Autogenerated by $generator */
#pragma once

#include <stdint.h>

typedef struct pmb887x_dsp_rom_t pmb887x_dsp_rom_t;

struct pmb887x_dsp_rom_t {
	uint16_t rom_version;
	const uint8_t *program_rom;
	const uint8_t *data_rom;
};

const pmb887x_dsp_rom_t *pmb887x_dsp_rom_find(uint16_t rom_version);
|;
close $header;

open my $source, '>', "$output_dir/dsp_rom.c" or die "open($output_dir/dsp_rom.c): $!";
print $source qq|/* Autogenerated by $generator */
#include "qemu/osdep.h"

#include "hw/arm/pmb887x/gen/dsp_rom.h"

|;
for my $image (@images) {
	print $source "static const uint8_t pmb887x_dsp_program_rom_$image->{rom_version}\[] = {\n";
	print $source dumpHex($image->{program});
	print $source "};\n\n";
	print $source "static const uint8_t pmb887x_dsp_data_rom_$image->{rom_version}\[] = {\n";
	print $source dumpHex($image->{data});
	print $source "};\n\n";
}

print $source "static const pmb887x_dsp_rom_t pmb887x_dsp_roms[] = {\n";
for my $image (@images) {
	my $rom_version = $image->{rom_version};
	print $source "\t{ 0x$rom_version, pmb887x_dsp_program_rom_$rom_version, pmb887x_dsp_data_rom_$rom_version },\n";
}
print $source qq|};

const pmb887x_dsp_rom_t *pmb887x_dsp_rom_find(uint16_t rom_version) {
	for (size_t i = 0; i < ARRAY_SIZE(pmb887x_dsp_roms); i++) {
		const pmb887x_dsp_rom_t *rom = &pmb887x_dsp_roms[i];
		if (rom->rom_version == rom_version)
			return rom;
	}
	return NULL;
}
|;
close $source;
